name: Sync Fork

on:
  schedule:
    - cron: '* */3 * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.TOKEN }}
          owner: BrookeAFK
          head: main
          base: main
