name: Sync Fork

on:
  schedule:
    - cron: '* */6 * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          token: ${{ secrets.TOKEN }}
          owner: BrookeAFK
          head: main
          base: main
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: A demo job to delete workflow runs
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.2.0
        with:
          repository: TCmanna/brookeafk-api
          older-than-seconds: 86400
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
